blueprint:
  name: ASHP Fixed Flow Temperature Control
  description: Controls ASHP fixed flow temperature based on outdoor and indoor temperatures with 15-minute polling
  domain: automation
  input:
    target_room_temp:
      name: Target Room Temperature
      description: Desired average room temperature (default 21°C)
      default: 21
      selector:
        number:
          min: 18
          max: 24
          step: 0.5
          unit_of_measurement: "°C"
    
    min_flow_temp:
      name: Minimum Flow Temperature
      description: Minimum allowed flow temperature
      default: 23
      selector:
        number:
          min: 20
          max: 30
          step: 1
          unit_of_measurement: "°C"
    
    max_flow_temp:
      name: Maximum Flow Temperature
      description: Maximum allowed flow temperature
      default: 55
      selector:
        number:
          min: 40
          max: 60
          step: 1
          unit_of_measurement: "°C"
    
    curve_oat_low:
      name: Weather Compensation - Low OAT Point
      description: Outdoor temperature for coldest design point
      default: -20
      selector:
        number:
          min: -30
          max: 0
          step: 1
          unit_of_measurement: "°C"
    
    curve_flow_high:
      name: Weather Compensation - High Flow Temperature
      description: Flow temperature at low OAT point
      default: 38
      selector:
        number:
          min: 25
          max: 60
          step: 1
          unit_of_measurement: "°C"
    
    curve_oat_high:
      name: Weather Compensation - High OAT Point
      description: Outdoor temperature for warmest design point
      default: 30
      selector:
        number:
          min: 10
          max: 35
          step: 1
          unit_of_measurement: "°C"
    
    curve_flow_low:
      name: Weather Compensation - Low Flow Temperature
      description: Flow temperature at high OAT point
      default: 23
      selector:
        number:
          min: 20
          max: 35
          step: 1
          unit_of_measurement: "°C"
    
    room_temp_adjustment:
      name: Room Temperature Adjustment Factor
      description: Flow temperature adjustment per °C room temperature error (default 1.0)
      default: 1.0
      selector:
        number:
          min: 0
          max: 3
          step: 0.1
          unit_of_measurement: "°C"

trigger:
  - platform: time_pattern
    minutes: "/15"

condition: []

action:
  - variables:
      # Get current temperatures from sensors
      outdoor_temp: "{{ states('sensor.ashp_outdoor_air_temperature_remote_sensor') | float(0) }}"
      room_temp: "{{ states('sensor.average_room_temperature') | float(21) }}"
      
      # Get blueprint inputs - use direct reference without templates
      target_temp: !input target_room_temp
      min_flow: !input min_flow_temp
      max_flow: !input max_flow_temp
      oat_low: !input curve_oat_low
      flow_high: !input curve_flow_high
      oat_high: !input curve_oat_high
      flow_low: !input curve_flow_low
      room_adj: !input room_temp_adjustment
      
      # Calculate temperature error (positive = room too cold, negative = room too warm)
      temp_error: "{{ target_temp - room_temp }}"
      
      # Weather compensation curve calculation
      base_flow: >
        {% set oat_range = oat_high - oat_low %}
        {% set flow_range = flow_high - flow_low %}
        {% set slope = flow_range / oat_range %}
        {% set flow = flow_high - (slope * (outdoor_temp - oat_low)) %}
        {{ [min_flow, [flow, max_flow] | min] | max }}
      
      # Apply room temperature compensation
      temp_adjustment: "{{ temp_error * room_adj }}"
      
      # Calculate final flow temperature
      calculated_flow: >
        {{ ([min_flow, [base_flow | float + temp_adjustment, max_flow] | min] | max) | round(1) }}
      
      # Convert to modbus value (x10)
      modbus_value: "{{ (calculated_flow * 10) | int }}"

  - service: modbus.write_register
    data:
      hub: aerona3
      slave: 1
      address: 2
      value: "{{ modbus_value }}"

  - service: logbook.log
    data:
      name: ASHP Flow Temperature Control
      message: >
        Set flow temp to {{ calculated_flow }}°C ({{ modbus_value }})
        OAT: {{ outdoor_temp }}°C, Room: {{ room_temp }}°C (Target: {{ target_temp }}°C)
        Base curve: {{ base_flow | round(1) }}°C, Adjustment: {{ temp_adjustment | round(1) }}°C

mode: single
